[package]
name = "banshee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
