//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::ban::Entity as Ban;
pub use super::report::Entity as Report;
pub use super::user::Entity as User;
pub use super::whitelist::Entity as Whitelist;
