//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub snowflake: i64,
    pub banned: bool,
    pub super_user: bool,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ban::Entity")]
    Ban,
    #[sea_orm(has_many = "super::whitelist::Entity")]
    Whitelist,
}

impl Related<super::ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ban.def()
    }
}

impl Related<super::whitelist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Whitelist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
